apiVersion: v1
kind: LimitRange
metadata:
  name: k8-limits-1
spec:
  limits:
    - type: Container
      default:
        cpu: 1
        memory: 512Mi
      defaultRequest:
        cpu: 0.5
        memory: 256Mi