apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-1
  namespace: dev
  labels:
    app: pod
    env: local
spec:
  securityContext:
    runAsUser: 1001
  serviceAccountName: k8-sa-1
  containers:
    -  name: nginx-1
       image: nginx
       readinessProbe:
         initialDelaySeconds: 10
         periodSeconds: 5
         failureThreshold: 5
         successThreshold: 2
         timeoutSeconds: 1
         httpGet:
           path: "/food"
           port: 8080
         tcpSocket:
           host: "mysql-svc"
           port: 3306
         exec:
           command:
             - "/bin/sh"
             - "-c"
             - "ls /usr/share/"
       livenessProbe:
         initialDelaySeconds: 20
         periodSeconds: 5
         failureThreshold: 5
         successThreshold: 1
         timeoutSeconds: 1
         httpGet:
           path: "/food"
           port: 8080
         tcpSocket:
           host: "mysql-svc"
           port: 3306
         exec:
           command:
             - "/bin/sh"
             - "-c"
             - "ls /usr/share/"
       command:
         - "sleep"
       args:
         - "500"
       securityContext:
         runAsUser: 1000
         capabilities:
           add:
             - "MAC_ADMIN"
       
