apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-2
  namespace: test
  labels:
    app: pod
    env: local
spec:
  volumes:
    - name: k8-vol-1
      secret:
        secretName: k8-sec-1
        defaultMode: 0755
  containers:
    - name: nginx-2
      image: nginx
      env:
        - name: maven
          valueFrom:
            secretKeyRef:
              key: MAVEN
              name: k8-sec-1
      envFrom:
        - secretRef:
            name: k8-sec-1