apiVersion: v1
kind: Pod
metadata:
  name: k8-pod-4
  labels:
    env: sandbox
spec:
  nodeSelector:
    env: "dev"
  tolerations:
    - key: "env"
      operator: Equal
      effect: "NoSchedule"
      value: "dev"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "env"
              operator: In
              values:
                - "dev"
                - "test"
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: "env"
              operator: In
              values:
                - "dev"
                - "test"
          weight: 0
  containers:
    - name: nginx-4
      image: nginx
      resources:
        limits:
          cpu: "5"
          memory: "20Gi"
        requests:
          cpu: "2"
          memory: "10Gi"