apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8-pv-1
spec:
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/dir
    type: Directory