apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-dev-1
  namespace: dev
spec:
  hard:
    pods: "1"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "10"
    resourcequotas: "1"
    secrets: "5"
    services: "3"