apiVersion: v1
kind: ReplicationController
metadata:
  name: k8-rc-1
  labels:
    env: local
spec:
  template:
    metadata:
      labels:
        app: pod
        env: local
    spec:
      containers:
        -  name: nginx-rc
           image: nginx
  replicas: 4
  